name: Deploy WinGet REST source (d4rk0)

on:
  workflow_dispatch:
    inputs:
      source_name:
        description: "Nombre visible del origen"
        required: true
        type: string
        default: d4rk0
      resource_group:
        description: "Resource Group destino"
        required: true
        type: string
        default: rg-darko-winget
      region:
        description: "Azure region (ej. westeurope)"
        required: true
        type: string
        default: westeurope
      performance:
        description: "Developer | Basic | Enhanced"
        required: true
        type: choice
        options: [Developer, Basic, Enhanced]
        default: Developer
      publisher_name:
        description: "Publisher name mostrado por el source"
        required: false
        type: string
        default: d4rk0

permissions:
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Preflight: secrets y suscripción
        shell: bash
        env:
          PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
        run: |
          set -euo pipefail
          [ -z "${PUBLISHER_EMAIL:-}" ] && { echo "Falta el secret PUBLISHER_EMAIL"; exit 1; }
          az account show --query id -o tsv >/dev/null

      - name: Preflight: providers
        shell: bash
        run: |
          set -euo pipefail
          need=(Microsoft.Web Microsoft.DocumentDB Microsoft.Storage Microsoft.Insights Microsoft.OperationalInsights Microsoft.KeyVault Microsoft.AppConfiguration Microsoft.ApiManagement)
          notok=()
          for ns in "${need[@]}"; do
            st=$(az provider show -n "$ns" --query registrationState -o tsv || true)
            [ "$st" != "Registered" ] && notok+=("$ns:$st")
          done
          if [ ${#notok[@]} -gt 0 ]; then
            printf 'Providers no registrados: %s\n' "${notok[@]}"
            exit 1
          fi

      - name: Preflight: permisos RBAC en el RG
        shell: bash
        run: |
          set -euo pipefail
          rg="${{ inputs.resource_group }}"
          rgid=$(az group show -n "$rg" --query id -o tsv)
          sp_appid=$(az account show --query user.name -o tsv)
          sp_id=$(az ad sp show --id "$sp_appid" --query id -o tsv)
          az role assignment create --assignee "$sp_id" --role Reader --scope "$rgid" >/dev/null
          az role assignment delete --assignee "$sp_id" --role Reader --scope "$rgid" >/dev/null

      - name: Preflight: comprobar Free Tier de Cosmos en la suscripción
        shell: bash
        run: |
          set -euo pipefail
          used=$(az cosmosdb list --query "[?enableFreeTier==\`true\`].[name,resourceGroup]" -o tsv | wc -l | tr -d ' ')
          if [ "$used" -gt 0 ] && [ "${{ inputs.performance }}" = "Developer" ]; then
            echo "Ya existe una cuenta Cosmos Free Tier en esta suscripción. Cambia de suscripción o usa 'Basic'."
            exit 1
          fi

      - name: Install WinGet REST module
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name Microsoft.WinGet.RestSource -AllowPrerelease -Force

      - name: Ensure App Configuration pass-through
        shell: bash
        run: |
          set -euo pipefail
          rg="${{ inputs.resource_group }}"
          loc="${{ inputs.region }}"
          name="${{ inputs.source_name }}"
          appcs="appcs-${name}"
          az appconfig show -g "$rg" -n "$appcs" >/dev/null 2>&1 || \
            az appconfig create -g "$rg" -n "$appcs" -l "$loc" --sku Free --arm-auth-mode pass-through
          az appconfig update -g "$rg" -n "$appcs" --arm-auth-mode pass-through

      - name: Deploy REST source (Functions + Cosmos)
        shell: pwsh
        env:
          SOURCE_NAME: ${{ inputs.source_name }}
          AZ_RESOURCE_GROUP: ${{ inputs.resource_group }}
          AZ_REGION: ${{ inputs.region }}
          PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
          PUBLISHER_NAME: ${{ inputs.publisher_name }}
          PERF: ${{ inputs.performance }}
        run: |
          $ErrorActionPreference = 'Stop'
          if (-not (Get-Module -ListAvailable Microsoft.WinGet.RestSource)) {
            Install-Module Microsoft.WinGet.RestSource -Scope CurrentUser -Force -AllowPrerelease
          }
          $max = 5
          for ($i = 1; $i -le $max; $i++) {
            try {
              New-WinGetSource `
                -Name "$env:SOURCE_NAME" `
                -ResourceGroup "$env:AZ_RESOURCE_GROUP" `
                -Region "$env:AZ_REGION" `
                -ImplementationPerformance "$env:PERF" `
                -PublisherName "$env:PUBLISHER_NAME" `
                -PublisherEmail "$env:PUBLISHER_EMAIL" `
                -ShowConnectionInstructions `
                -InformationAction Continue `
                -Verbose
              break
            } catch {
              if ($i -eq $max) { throw }
              Start-Sleep -Seconds (30 * $i)
            }
          }

      - name: Verify Cosmos Free Tier result
        shell: bash
        run: |
          set -euo pipefail
          rg="${{ inputs.resource_group }}"
          list=$(az cosmosdb list -g "$rg" --query "[].{name:name,free:enableFreeTier}" -o tsv)
          [ -z "$list" ] && { echo "No Cosmos DB en RG"; exit 1; }
          echo "$list" | awk '{print $1" freeTier="$2}'
          echo "$list" | awk '{print $2}' | grep -q "true" || { echo "La cuenta Cosmos del RG no está en Free Tier"; exit 1; }

      - name: Cap Application Insights to 0.1 GB/day
        shell: pwsh
        run: |
          Install-Module Az.ApplicationInsights -Force
          $rg = "${{ inputs.resource_group }}"
          $apps = Get-AzApplicationInsights -ResourceGroupName $rg
          if ($apps) { foreach ($a in $apps) { Set-AzApplicationInsightsDailyCap -ResourceGroupName $rg -Name $a.Name -DailyCapGB 0.1 -DisableNotificationWhenHitCap } }

      - name: Show winget add command
        shell: pwsh
        run: |
          $rg = "${{ inputs.resource_group }}"
          $name = "${{ inputs.source_name }}"
          $apim = az apim list -g $rg --query "[?contains(name,'$name')][0].gatewayUrl" -o tsv
          if (-not $apim) { $apim = az apim list -g $rg --query "[0].gatewayUrl" -o tsv }
          if ($apim) { Write-Host "winget source add -n $name -t Microsoft.Rest -a $apim/winget/" } else { Write-Host "No APIM found" }
